script_name=prod_an_mask5

executable            = sub.sh
universe	      = vanilla
requirements          = (OpSysAndVer =?= "CentOS7")
arguments             = $(ProcId) 5
output                = output/$(script_name).$(ClusterId).$(ProcId).$(Step).out
error                 = error/$(script_name).$(ClusterId).$(ProcId).$(Step).err
log                   = log/$(script_name).$(ClusterId).log
RequestCpus	      = 1
+JobFlavour = "longlunch"
queue 100